### ISSUE TITLE
`verdi archive import` fails for `sqlite_dos` backend on `conda`-based AiiDA installation

### ISSUE THREAD

**Issue by GeigerJ2** [SwissDataScienceCenter/contributed-project-templates#86]
Alright, not sure yet where this originates from, but I just realized that importing an archive into the `sqlite_dos` backend actually fails for a `conda`-based installation in the AiiDA template. The issue first occured for an archive that had to be migrated on the fly, but the error persists when migrating the archive before.

When creating a python `venv` and installing AiiDA instead, the issue doesn't occur. In general, I'm becoming quite inclined to change the template to use `venv` rather than `conda` anyway. PostgreSQL doesn't work currently either way, so we are using SQLite. As the idea is to explore existing archives from Materials Cloud Archive, rather than running workflows, RabbitMQ is not required either, so there's no reason to use `conda` instead of `venv`. As soon as AiiDA v2.6 is released, I'll update the template, using the service-less new `verdi presto` profile setup command, and with it make sure that this issue here is resolved.

Below are the two tracebacks attached for future reference:

Re-raising [here](https://github.com/aiidateam/aiida-core/blob/c2ca6423c1803f75ef198f896cb8ba85339be3ff/src/aiida/cmdline/commands/cmd_archive.py#L521-L522) gives:
```python
verdi archive import 'https://archive.materialscloud.org/record/file?filename=acwf-verification_unaries-verification-PBE-v1_results_gpaw.aiida&file_id=b82dadcf-9d5e-4ef8-8a74-3af8711ab1d2&record_id=1770'
Report: downloading archive: https://archive.materialscloud.org/record/file?filename=acwf-verification_unaries-verification-PBE-v1_results_gpaw.aiida&file_id=b82dadcf-9d5e-4ef8-8a74-3af8711ab1d2&record_id=1770
Success: archive downloaded, proceeding with import
Report: starting import: https://archive.materialscloud.org/record/file?filename=acwf-verification_unaries-verification-PBE-v1_results_gpaw.aiida&file_id=b82dadcf-9d5e-4ef8-8a74-3af8711ab1d2&record_id=1770
Report: incompatible version detected for https://archive.materialscloud.org/record/file?filename=acwf-verification_unaries-verification-PBE-v1_results_gpaw.aiida&file_id=b82dadcf-9d5e-4ef8-8a74-3af8711ab1d2&record_id=1770, trying migration
Report: Legacy migrations required from zip format
Report: Extracting data.json ...
Report: Legacy migration pathway: 0.10 -> 0.11 -> 0.12 -> 0.13
Report: legacy '0.13' -> 'main_0000' conversion required                                                                                                                                
Report: Initialising new archive...
Report: Unique repository files written: 13512                                                                                                                                          
Report: Converting DB to SQLite
Report: Performing SQLite migrations:                                                                                                                                                   
Report: - main_0000 -> main_0000a
Report: - main_0000a -> main_0000b
Report: - main_0000b -> main_0001
Report: Finalising the migration ...
Report: proceeding with import of migrated archive
Report: Parameters
-------------------------------  ----------------------
Archive                          migrated_archive.aiida
New Node Extras                  keep
Merge Node Extras (in database)  (k)eep
Merge Node Extras (in archive)   do (n)ot create
Merge Node Extras (in both)      (l)eave existing
Merge Comments                   leave
Computer Authinfos               exclude

Report: Adding 2 new user(s)
Traceback (most recent call last):                                                                                                                                                      
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/commands/cmd_archive.py", line 504, in _import_archive_and_migrate
    _import_archive(archive_path, archive_format=archive_format, **import_kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 136, in import_archive
    raise IncompatibleStorageSchema(
aiida.common.exceptions.IncompatibleStorageSchema: The archive version '0.10' is not the latest version 'main_0001'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/groups/verdi.py", line 117, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/utils/decorators.py", line 102, in wrapper
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/commands/cmd_archive.py", line 411, in import_archive
    _import_archive_and_migrate(ctx, archive, web_based, import_kwargs, migration)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/commands/cmdTracebacks for future reference:_archive.py", line 517, in _import_archive_and_migrate
    _import_archive(archive_path, archive_format=archive_format, **import_kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 168, in import_archive
    user_ids_archive_backend = _import_users(backend_from, backend, query_params)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 281, in _import_users
    _add_new_entities(
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 246, in _add_new_entities
    new_ids = backend_to.bulk_insert(etype, rows)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/storage/psql_dos/backend.py", line 337, in bulk_insert
    result = session.execute(insert(mapper).returning(mapper, column('id')), rows).fetchall()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1268, in orm_execute_statement
    result = _bulk_insert(verdi archive import 'https://archive.materialscloud.org/record/file?filename=acwf-verification_unaries-verification-PBE-v1_results_gpaw.aiida&file_id=b82dadcf-9d5e-4ef8-8a74-3af8711ab1d2&record_id=1770'
Report: downloading archive: https://archive.materialscloud.org/record/file?filename=acwf-verification_unaries-verification-PBE-v1_results_gpaw.aiida&file_id=b82dadcf-9d5e-4ef8-8a74-3af8711ab1d2&record_id=1770
Success: archive downloaded, proceeding with import
Report: starting import: https://archive.materialscloud.org/record/file?filename=acwf-verification_unaries-verification-PBE-v1_results_gpaw.aiida&file_id=b82dadcf-9d5e-4ef8-8a74-3af8711ab1d2&record_id=1770
Report: incompatible version detected for https://archive.materialscloud.org/record/file?filename=acwf-verification_unaries-verification-PBE-v1_results_gpaw.aiida&file_id=b82dadcf-9d5e-4ef8-8a74-3af8711ab1d2&record_id=1770, trying migration
Report: Legacy migrations required from zip format
Report: Extracting data.json ...
Report: Legacy migration pathway: 0.10 -> 0.11 -> 0.12 -> 0.13
Report: legacy '0.13' -> 'main_0000' conversion required                                                                                                                                
Report: Initialising new archive...
Report: Unique repository files written: 13512                                                                                                                                          
Report: Converting DB to SQLite
Report: Performing SQLite migrations:                                                                                                                                                   
Report: - main_0000 -> main_0000a
Report: - main_0000a -> main_0000b
Report: - main_0000b -> main_0001
Report: Finalising the migration ...
Report: proceeding with import of migrated archive
Report: Parameters
-------------------------------  ----------------------
Archive                          migrated_archive.aiida
New Node Extras                  keep
Merge Node Extras (in database)  (k)eep
Merge Node Extras (in archive)   do (n)ot create
Merge Node Extras (in both)      (l)eave existing
Merge Comments                   leave
Computer Authinfos               exclude

Report: Adding 2 new user(s)
Traceback (most recent call last):                                                                                                                                                      
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/commands/cmd_archive.py", line 504, in _import_archive_and_migrate
    _import_archive(archive_path, archive_format=archive_format, **import_kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 136, in import_archive
    raise IncompatibleStorageSchema(
aiida.common.exceptions.IncompatibleStorageSchema: The archive version '0.10' is not the latest version 'main_0001'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/groups/verdi.py", line 117, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/utils/decorators.py", line 102, in wrapper
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/commands/cmd_archive.py", line 411, in import_archive
    _import_archive_and_migrate(ctx, archive, web_based, import_kwargs, migration)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/commands/cmd_archive.py", line 517, in _import_archive_and_migrate
    _import_archive(archive_path, archive_format=archive_format, **import_kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 168, in import_archive
    user_ids_archive_backend = _import_users(backend_from, backend, query_params)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 281, in _import_users
    _add_new_entities(
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 246, in _add_new_entities
    new_ids = backend_to.bulk_insert(etype, rows)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/storage/psql_dos/backend.py", line 337, in bulk_insert
    result = session.execute(insert(mapper).returning(mapper, column('id')), rows).fetchall()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1268, in orm_execute_statement
    result = _bulk_insert(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 200, in _bulk_insert
    result = persistence._emit_insert_statements(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1133, in _emit_insert_statements
    result = connection.execute(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1629, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 671, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1426, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 867, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/annotation.py", line 351, in _compiler_dispatch
    return self.__element.__class__._compiler_dispatch(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 5603, in visit_insert
    compile_state = insert_stmt._compile_state_factory(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 678, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1327, in create_for_statement
    self._setup_for_bulk_insert(compiler)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1380, in _setup_for_bulk_insert
    statement = self._setup_orm_returning(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 536, in _setup_orm_returning
    fsc.setup_dml_returning_compile_state(dml_mapper)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 846, in setup_dml_returning_compile_state
    entity.setup_dml_returning_compile_state(self, adapter)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 2501, in setup_dml_returning_compile_state
    raise NotImplementedError()
NotImplementedError
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 200, in _bulk_insert
    result = persistence._emit_insert_statements(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1133, in _emit_insert_statements
    result = connection.execute(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1629, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 671, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1426, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 867, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/annotation.py", line 351, in _compiler_dispatch
    return self.__element.__class__._compiler_dispatch(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 5603, in visit_insert
    compile_state = insert_stmt._compile_state_factory(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 678, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1327, in create_for_statement
    self._setup_for_bulk_insert(compiler)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1380, in _setup_for_bulk_insert
    statement = self._setup_orm_returning(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 536, in _setup_orm_returning
    fsc.setup_dml_returning_compile_state(dml_mapper)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 846, in setup_dml_returning_compile_state
    entity.setup_dml_returning_compile_state(self, adapter)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 2501, in setup_dml_returning_compile_state
    raise NotImplementedError()
NotImplementedError
```

While migrating the archive before and then trying to import, re-raising [here](https://github.com/aiidateam/aiida-core/blob/c2ca6423c1803f75ef198f896cb8ba85339be3ff/src/aiida/cmdline/commands/cmd_archive.py#L531-L532) gives:

```python
verdi archive import acwf-gpaw-migrated.aiida 
Report: starting import: acwf-gpaw-migrated.aiida
Report: Parameters
-------------------------------  ------------------------
Archive                          acwf-gpaw-migrated.aiida
New Node Extras                  keep
Merge Node Extras (in database)  (k)eep
Merge Node Extras (in archive)   do (n)ot create
Merge Node Extras (in both)      (l)eave existing
Merge Comments                   leave
Computer Authinfos               exclude

Report: Adding 2 new user(s)
Traceback (most recent call last):                                                                                                                                                      
  File "/opt/conda/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/groups/verdi.py", line 117, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/utils/decorators.py", line 102, in wrapper
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/commands/cmd_archive.py", line 411, in import_archive
    _import_archive_and_migrate(ctx, archive, web_based, import_kwargs, migration)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/cmdline/commands/cmd_archive.py", line 504, in _import_archive_and_migrate
    _import_archive(archive_path, archive_format=archive_format, **import_kwargs)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 168, in import_archive
    user_ids_archive_backend = _import_users(backend_from, backend, query_params)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 281, in _import_users
    _add_new_entities(
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/tools/archive/imports.py", line 246, in _add_new_entities
    new_ids = backend_to.bulk_insert(etype, rows)
  File "/home/jovyan/work/materials-cloud-archive-aiida-common-workflows-aiida/notebooks/aiida-core/src/aiida/storage/psql_dos/backend.py", line 337, in bulk_insert
    result = session.execute(insert(mapper).returning(mapper, column('id')), rows).fetchall()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1268, in orm_execute_statement
    result = _bulk_insert(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 200, in _bulk_insert
    result = persistence._emit_insert_statements(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1133, in _emit_insert_statements
    result = connection.execute(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1629, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 671, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1426, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 867, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/annotation.py", line 351, in _compiler_dispatch
    return self.__element.__class__._compiler_dispatch(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 5603, in visit_insert
    compile_state = insert_stmt._compile_state_factory(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 678, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1327, in create_for_statement
    self._setup_for_bulk_insert(compiler)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1380, in _setup_for_bulk_insert
    statement = self._setup_orm_returning(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 536, in _setup_orm_returning
    fsc.setup_dml_returning_compile_state(dml_mapper)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 846, in setup_dml_returning_compile_state
    entity.setup_dml_returning_compile_state(self, adapter)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 2501, in setup_dml_returning_compile_state
    raise NotImplementedError()
NotImplementedError
```

**Comment by rokroskar** [comment]
That sounds good @GeigerJ2 (regarding the changes to the image) - do you need help from our side?

**Comment by GeigerJ2** [comment]
Hi @rokroskar, I'll see to get around updating the template soon, as we've released v2.6. beginning of this month. It should be fine, probably just a PR review then :) Cheers!
